### ISSUE TITLE
pp. 64 第15题的文件potus.xml无法获得

### ISSUE THREAD

**Issue by realalien** [coderLMN/AutomatedDataCollectionWithR#15]
[http://www.r-datacollection.com/materials.html](url) 报404错误。第三章的练习，第15题(第64页)需要的源文件potus.xml找不到。请求提供

**Comment by coderLMN** [comment]
材料网址是 http://www.r-datacollection.com/materials ，你用的网址后面多了个 `.html` 所以出现了 404 错误。

potus.xml 被放在第 4 章的材料里了，网址是 http://www.r-datacollection.com/materials/ch-4-xpath/potus/potus.xml 。

**Comment by realalien** [comment]
谢谢，收到！
