### ISSUE TITLE
P39 indy<-fromJSON(content = "indy.json") 错误

### ISSUE THREAD

**Issue by dxh8286239** [coderLMN/AutomatedDataCollectionWithR#17]
老师，JSON对象转化错误，提示为
> indy <- fromJSON("indy.json")
Error in nchar(content) : invalid multibyte string, element 1
这是什么问题啊？

**Comment by coderLMN** [comment]
看这个，有一位读者已经解决了，完全一样的问题 https://github.com/coderLMN/AutomatedDataCollectionWithR/issues/11

**Comment by dxh8286239** [comment]
谢谢老师~
