### ISSUE TITLE
老师您好，请问怎样才能创建有效的重定向URI？

### ISSUE THREAD

**Issue by AXGL** [coderLMN/AutomatedDataCollectionWithR#22]
![C99E85C4-8C6C-4480-A0CF-58242B36B174](https://user-images.githubusercontent.com/56990919/81729205-2ee9e900-94be-11ea-9b8a-08085fcabfff.png)

**Comment by AXGL** [comment]
就是在创建雅虎应用时要填写的redirect uri那一栏不知道怎么写
这里是因为使用雅虎天气的API需要创建应用

**Comment by AXGL** [comment]
这里是因为使用雅虎天气的API需要创建应用

**Comment by coderLMN** [comment]
抱歉刚看到你的问题。这个 uri 就是你的程序的服务器地址，即 yahoo 接口返回信息的目标地址。例如，用 R 的 httr 组件调用 oauth_callback() 获取回调 URL，一般得到的这个 uri 就是 http://localhost:1410/ 。你也可以参考我整理的 wiki 第九章部分： https://github.com/coderLMN/AutomatedDataCollectionWithR/wiki/%E7%AC%AC-9-%E7%AB%A0

**Comment by AXGL** [comment]
> 抱歉刚看到你的问题。这个 uri 就是你的程序的服务器地址，即 yahoo 接口返回信息的目标地址。例如，用 R 的 httr 组件调用 oauth_callback() 获取回调 URL，一般得到的这个 uri 就是 http://localhost:1410/ 。你也可以参考我整理的 wiki 第九章部分： https://github.com/coderLMN/AutomatedDataCollectionWithR/wiki/%E7%AC%AC-9-%E7%AB%A0

谢谢老师，我已经找到了，在看你前面和另一个人的回答中发现了使用oauth_callback()可以回调这个地址。
